### ISSUE TITLE
Specify seconds in cron

### ISSUE THREAD

**Issue by MaryCooperGD** [if6was9/cron4j#1]
Since cron expressions accept seconds too, I wanted to ask if it's possible to modify the expression in cron4j to manage seconds too.

**Comment by if6was9** [comment]
I’m not the maintainer of cron4j.  I think the maintainer has the code on SourceForge.  I just imported it to GitHub for my own reference. 

I have used it for years and it works very well. 

I can tell you that it’s not really set up to handle seconds.  Existing user-implementations that generate the task-table may not be happy if they are run 60x as frequently.  

It’s doable.  But may require some care to get it right.
